
- name: Home
  icon: dashboard
  router: "/dashboard"
  order: 9
- name: System Management
  icon: setting
  order: 7
  children:
    - name: Menu management
      icon: solution
      router: "/system/menu"
      order: 9
      actions:
        - code: add
          name: Add
          resources:
            - method: POST
              path: "/api/v1/menus"
        - code: edit
          name: update
          resources:
            - method: GET
              path: "/api/v1/menus/:id"
            - method: PUT
              path: "/api/v1/menus/:id"
        - code: del
          name: delete
          resources:
            - method: DELETE
              path: "/api/v1/menus/:id"
        - code: query
          name: Query
          resources:
            - method: GET
              path: "/api/v1/menus"
            - method: GET
              path: "/api/v1/menus.tree"
        - code: disable
          name: Disable
          resources:
            - method: PATCH
              path: "/api/v1/menus/:id/disable"
        - code: enable
          name: Enable
          resources:
            - method: PATCH
              path: "/api/v1/menus/:id/enable"
    - name: Role management
      icon: audit
      router: "/system/role"
      order: 8
      actions:
        - code: add
          name: Add
          resources:
            - method: GET
              path: "/api/v1/menus.tree"
            - method: POST
              path: "/api/v1/roles"
        - code: edit
          name: Edit
          resources:
            - method: GET
              path: "/api/v1/menus.tree"
            - method: GET
              path: "/api/v1/roles/:id"
            - method: PUT
              path: "/api/v1/roles/:id"
        - code: del
          name: Delete
          resources:
            - method: DELETE
              path: "/api/v1/roles/:id"
        - code: query
          name: List
          resources:
            - method: GET
              path: "/api/v1/roles"
        - code: disable
          name: Disable
          resources:
            - method: PATCH
              path: "/api/v1/roles/:id/disable"
        - code: enable
          name: Enable
          resources:
            - method: PATCH
              path: "/api/v1/roles/:id/enable"
    - name: User Management
      icon: user
      router: "/system/user"
      order: 7
      actions:
        - code: add
          name: Add
          resources:
            - method: GET
              path: "/api/v1/roles.select"
            - method: POST
              path: "/api/v1/users"
        - code: edit
          name: Edit
          resources:
            - method: GET
              path: "/api/v1/roles.select"
            - method: GET
              path: "/api/v1/users/:id"
            - method: PUT
              path: "/api/v1/users/:id"
        - code: del
          name: Delete
          resources:
            - method: DELETE
              path: "/api/v1/users/:id"
        - code: query
          name: List
          resources:
            - method: GET
              path: "/api/v1/users"
        - code: disable
          name: Disable
          resources:
            - method: PATCH
              path: "/api/v1/users/:id/disable"
        - code: enable
          name: Enable
          resources:
            - method: PATCH
              path: "/api/v1/users/:id/enable"
